### ISSUE TITLE
The wafer ID in DUT Summary is not the real wafer ID

### ISSUE THREAD

**Issue by Saintzju** [noonchen/STDF-Viewer#108]
The wafer ID in DUT summary is not the real wafer ID but the Sequence number of this wafer.

![image](https://user-images.githubusercontent.com/105335189/170063049-e7e2d98c-b9eb-41b5-9961-6c77a4ddbed7.png)

**Comment by noonchen** [comment]
You're right, it's designed to show the wafer index here. However, as you mentioned, the actual Wafer_ID would be more helpful.

**Comment by noonchen** [comment]
fixed in v4.0.0 branch, closing
