### ISSUE TITLE
MacOS Monterey 12.4 can't detect the application as safe

### ISSUE THREAD

**Issue by kashishshah88** [noonchen/STDF-Viewer#109]
Hi,

MacOS Monterey 12.4 can't detect the application as safe so it won't let use the tool.
Any workaround for this? Thanks.

**Comment by noonchen** [comment]
You can always force MacOS to run apps.

Go to `System Preferences -> Security & Privacy -> General -> Open Anyway`

**Comment by noonchen** [comment]
Hi @kashishshah88 , this issue is more like a macOS's behaviour instead of a software bug, I'll close this one
