### ISSUE TITLE
Error when loading V4-2007 STDF in V3.4.0

### ISSUE THREAD

**Issue by Zhenyu-Yu** [noonchen/STDF-Viewer#111]
所选STD路径： 
D:/Production/XXXX/XXXXX_NIV_t126_XXXXX_01_XXXXX_N4_CP2_M40C_20220725_23h54.stdf
读取中...
##### 报告开始 #####
Byte Order: little endian
FAR × 1
ATR × 1
INVAILD_STDF

Total wafers: 0
Total duts/dies: 0
Total records: 2
Analysis Finished

**Comment by flob05** [comment]
Hi,

I have the same problem.
Running it with Version V3.3 everything is fine, but V3.4 reports that the STDF is invalid.
Is there any log with more detailed information what is invalid?

Thank you very much!

**Comment by noonchen** [comment]
@Zhenyu-Yu  @flob05 

The latest version uses a strong check, whereas the v3.3 will skip any records that are not recognized.

The error is due to the new records introduced in V2007-1, it is under dev right now

**Comment by noonchen** [comment]
fixed in v4.0.0 branch, closing
