### ISSUE TITLE
Generating an Excel report via command line

### ISSUE THREAD

**Issue by elca-chen** [noonchen/STDF-Viewer#113]
I'm able to generate a csv/xlsx report manually, and I'm wondering if I can generate the report by command line so that Ii can be merged into the test flow.

Thanks

**Comment by noonchen** [comment]
This app is strongly coupled with GUI, it would be too late for command line support... sorry about that.

however, it is possible to write a py script from scratch, it won't be too hard since the file reading, parsing and data exporting functions can be used for references.
