### ISSUE TITLE
Can the tool be used from the CLI to convert STDF to XLSX?

### ISSUE THREAD

**Issue by BrowniesBox** [noonchen/STDF-Viewer#141]
Use case: 
I want to use the tool in a data pipeline to process multiple STDF files (That's why I only need the conversion).

Thanks!

**Comment by matt-beyer** [comment]
I think you might want rust-stdf or pystdf
https://github.com/noonchen/rust-stdf
https://github.com/cmars/pystdf

**Comment by noonchen** [comment]
Hi @BrowniesBox ,

This tool's main objective is to visualize STDF, as for your request, that would be out of my scope :(

If you're looking for stdf to xlsx converter, there is an example you might find helpful in https://github.com/noonchen/rust-stdf.
