### ISSUE TITLE
关于STDF-Viewer工程缺少“rust_stdf_helper”的问题

### ISSUE THREAD

**Issue by zhanghui01** [noonchen/STDF-Viewer#145]
Dear  Sir:
      你写的项目太棒了，但我是个python新手。打包你的源码后用pycharm运行该项目总是提示：ModuleNotFoundError: No module named 'rust_stdf_helper'；请问这个是在你的另外一个项目里吗？这个是R语言写的？如何解决这个问题呢？非常期待你的回答。

**Comment by zhanghui01** [comment]
问题已解决： 
1. 安装rust环境 
2. 安装python库 maturin 
3. cd到helper的目录下（cargo.toml所在路径），运行maturin build -f  -r 
4. 在target/wheel下会生成一个whl包，用pip安装即可。
感谢作者！！！

**Comment by noonchen** [comment]
This issue is solved via email, closing.

**Comment by zhangand** [comment]
could you please also forward the debug env setup to me, thanks

**Comment by xlcolin** [comment]
> 问题已解决：
> 
> 1. 安装rust环境
> 2. 安装python库 maturin
> 3. cd到helper的目录下（cargo.toml所在路径），运行maturin build -f  -r
> 4. 在target/wheel下会生成一个whl包，用pip安装即可。
>    感谢作者！！！



> 问题已解决：
> 
> 1. 安装rust环境
> 2. 安装python库 maturin
> 3. cd到helper的目录下（cargo.toml所在路径），运行maturin build -f  -r
> 4. 在target/wheel下会生成一个whl包，用pip安装即可。
>    感谢作者！！！

请问运行maturin build是要在python里面吗，我在python里运行显示 build是invalid syntax

**Comment by noonchen** [comment]
@xlcolin 这不是python的语句，直接在terminal里面运行maturin

**Comment by xlcolin** [comment]
> @xlcolin 这不是python的语句，直接在terminal里面运行maturin

😂😂在terminal里运行显示 'maturin' is not recognized as an internal or external command

**Comment by noonchen** [comment]
> > @xlcolin 这不是python的语句，直接在terminal里面运行maturin
> 
> 😂😂在terminal里运行显示 'maturin' is not recognized as an internal or external command

你是用pip安装的maturin吗？windows里安装完要关掉cmd重新打开一下才会更新PATH。

如果还是出现相同的错误，尝试去找maturin.exe的绝对路径吧，我暂时没遇到过这个情况。

**Comment by xlcolin** [comment]
> > > @xlcolin 这不是python的语句，直接在terminal里面运行maturin
> > 
> > 😂😂在terminal里运行显示 'maturin' is not recognized as an internal or external command
> 
> 你是用pip安装的maturin吗？windows里安装完要关掉cmd重新打开一下才会更新PATH。
> 
> 如果还是出现相同的错误，尝试去找maturin.exe的绝对路径吧，我暂时没遇到过这个情况。

已解决，定位到maturin.exe后把路径添加到PATH。感谢🙏
