### ISSUE TITLE
The test summary data is wrong

### ISSUE THREAD

**Issue by fkueihcihc** [noonchen/STDF-Viewer#149]
[U2M468#12_x3y1_STDF.zip](https://github.com/noonchen/STDF-Viewer/files/11454299/U2M468.12_x3y1_STDF.zip)
![image](https://github.com/noonchen/STDF-Viewer/assets/45201801/a150d7a2-a373-4a33-b0a7-62a69f9d37f2)

when i extract the stdf and save as csv, it's found that the value is wrong, the right value is 19123,but this tool displays 19100, it seems the 23  is missing

**Comment by noonchen** [comment]
<img width="602" alt="image" src="https://github.com/noonchen/STDF-Viewer/assets/26359487/ea5a9700-8443-4195-8836-2172ce554728">
I see the data is correct, closing~

**Comment by fkueihcihc** [comment]
got it,thx
