### ISSUE TITLE
Test data with the same test number is separated

### ISSUE THREAD

**Issue by lookc1983** [noonchen/STDF-Viewer#150]
![CaptureSTDF](https://github.com/noonchen/STDF-Viewer/assets/148409026/805dc258-930c-48e2-bb4b-a983de1982d4)

Hi

I am not sure why the test data with the same test number is separated into 2 instead combine into 1.
Is there anything that I miss out on this during the STDF loading?
Thanks

**Comment by noonchen** [comment]
Beacause of the new feature added for #91.

Some users reported that some tests would use a shared test number but using a different test name, looks like it is not compatible with your case...

**Comment by noonchen** [comment]
In the stdf spec, TEST_TXT is not an optional fields in test records, which means all test records should contain correct test name.

In your stdf, it looks like majority of your PTRs have an empty test name.

The issue you're facing should be fixed when you add same test name for all PTRs.

**Comment by lookc1983** [comment]
Thanks for your reply. Appreciated.
