### ISSUE TITLE
导入的怎么退出去

### ISSUE THREAD

**Issue by lifeyou** [noonchen/STDF-Viewer#157]
我将文件导入进去，但是一直就是这个文件，怎么换新的文件，把原来文件删除

**Comment by noonchen-ni** [comment]
启动的时候会自动加载上次关闭的文件
https://github.com/noonchen/STDF-Viewer/blob/c00412b2b32737a242daae1abc93653db156fa77/STDF-Viewer.py#L187

点下左上角的`Open`打开新的文件就行，不想要这个功能可以自行comment上面这行代码。

**Comment by lifeyou** [comment]
> 启动的时候会自动加载上次关闭的文件
> 
> https://github.com/noonchen/STDF-Viewer/blob/c00412b2b32737a242daae1abc93653db156fa77/STDF-Viewer.py#L187
> 
> 点下左上角的`Open`打开新的文件就行，不想要这个功能可以自行comment上面这行代码。

感谢您的回复
