### ISSUE TITLE
Can not open file path contains Unicode charachers

### ISSUE THREAD

**Issue by luhaun2010** [noonchen/STDF-Viewer#43]
![image](https://user-images.githubusercontent.com/78467600/123072029-c18de300-d447-11eb-9966-32158bb7fc90.png)
[STDF Viewer(1).log](https://github.com/noonchen/STDF-Viewer/files/6700650/STDF.Viewer.1.log)

**Comment by noonchen** [comment]
According to the given log, the stdf file can not be opened in cython module, I have reproduced a similar behavior on Windows when the path contains Unicode.

Can you try to move the file to a path that only contains ASCII (letters, numbers and underscore) and see if it still occurs?
