### ISSUE TITLE
Ingoring items of PTR with no limit

### ISSUE THREAD

**Issue by jinstrong** [noonchen/STDF-Viewer#56]
Please support show PTR test items with no limit.

**Comment by noonchen** [comment]
@jinstrong I didn't implement any logic to ignore certain PTR records. 

For PTR without limits, the code will assign the limits with a default value of 0:
https://github.com/noonchen/STDF-Viewer/blob/2d49bd2627effefd95d24726ab0c47d75e52fc15/deps/cystdf/stdf4_src/stdf4_func.c#L166

If you believe some test items are not showing up, you can send the stdf file and the missing test name(s) to my email: chennoon233@foxmail.com.

**Comment by noonchen** [comment]
No response in 3 weeks, closing.
