### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 4396clearlove7** [noonchen/STDF-Viewer#80]
Traceback (most recent call last):
  File "D:/STDF-Viewer/STDF-Viewer.py", line 41, in <module>
    from deps.DatabaseFetcher import DatabaseFetcher
  File "D:\STDF-Viewer\deps\DatabaseFetcher.py", line 47, in <module>
    class DatabaseFetcher:
  File "D:\STDF-Viewer\deps\DatabaseFetcher.py", line 353, in DatabaseFetcher
    def getWaferCoordsDict(self, waferIndex: int, head: int, site: int) -> dict[int, list]:
TypeError: 'type' object is not subscriptable

Process finished with exit code 1

**Comment by noonchen** [comment]
你的python版本太低了吧？看起来不支持`dict[int, list]`这种类型标注，我开发用的是python 3.9, 或者你把这个标注删了看看。

Possibly because of using an old version of python that doesn't support `dict[int, list]` type annotation. Try running with python3.9 or deleting all type annotations on your own.

**Comment by noonchen** [comment]
Python 3.9+ supports using built-in types in annotation, not a bug.

**Comment by 4396clearlove7** [comment]
感谢，删除标注后不报了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "noonchen/STDF-Viewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月19日(星期三) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [noonchen/STDF-Viewer] 启动报错 (Issue #80)





 
Python 3.9+ supports using built-in types in annotation, not a bug.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
