### ISSUE TITLE
Is there a part of the tool that reads Datalog Text Records (DTR)?

### ISSUE THREAD

**Issue by jbesancon-impinj** [noonchen/STDF-Viewer#82]
Hi, 
I love the tool, but it would be useful in my situation to be able to view Datalog Text Records (DTR). Is there a place where I can already see DTRs? If not, is this a possible feature to add?
Thank you,
Jimmy

**Comment by noonchen** [comment]
Hi,

It's easy to read DTRs from files and store the contents in the database, but how do you wish to view the data?

According to the spec, DTRs can be:

> Anywhere in the data stream after the initial sequence

To help me understand what you want to achieve, I need to know:
What kind of info you would store in DTRs? 
Is the location of DTRs in the file important to you?

**Comment by jbesancon-impinj** [comment]
My use case is storing any UUT error messages in the DTRs. If possible, it would be cool to have the DTRs parsed such that they associate with the UUT that generated them, but it seems like that might be difficult or maybe impossible. If so, it would be sufficient for my use to just view all the DTRs in an STDF in a text window somewhere in the viewer.

**Comment by noonchen** [comment]
@jbesancon-impinj DTRs don't have HEAD_NUM and SITE_NUM fields, it can not be associated with UUTs, because some multi-site STDF files have a structure like PIR-PIR-PIR-xxxxxx-PRR-PRR-PRR, without head & site you cannot know which UUT produced DTRs or GDRs.

But I add a approximate locations in the table, that might help you associate DTR with UUT.

**Comment by noonchen** [comment]
Github Action has build a EXE during the pr, you can try it out before final release:
https://github.com/noonchen/STDF-Viewer/actions/runs/1765998504

**Comment by sbazili** [comment]
Hi,
We also would like to see DTR support for unit UUT.
I suggest maybe adding custom configuration in the tool options, how to parse the DTR record and it will be saved for all STDF's.

For example, every user can configure regular expression or some format on the STR record :
DTR Record
  TEXT_DAT:      {SITE}:{UUT}: {Wafer}_{Lot}_{X}_{Y}_{Step}

**Comment by noonchen** [comment]
>  I suggest maybe adding custom configuration in the tool options, how to parse the DTR record and it will be saved for all STDF's.
> For example, every user can configure regular expression or some format on the STR record : DTR Record TEXT_DAT: {SITE}:{UUT}: {Wafer}_{Lot}_{X}_{Y}_{Step}

I'm not sure I understand your request. Say if a DTR contains a string "{0}:{1}:{1}{LotName}{0}{0}{StepName}", and I can extract the data from the regex pattern you provided, what are you expecting me to do with these extract data? what should happen if the string cannot be parsed?

**Comment by noonchen** [comment]
@sbazili 
Well, the main scope of my app is to **visualize** the test data, but what you described sounds like a very specialized use case of DTR.

This project is not very complex, I could give you some support on coding to help you achieve your goal, if you're interested.

**Comment by jbesancon-impinj** [comment]
Hi noonchen,
I saw you added a commit that say it added DTR viewing functionality. Do you have a timeline of when the next release will be out, or are you still working on it? Alternatively, do you have a stable pre-release build that I could perhaps try out?
Thanks,
Jimmy

**Comment by noonchen** [comment]
Hi @jbesancon-impinj , the DTR functionality is ready, but I'd like to release it with other features, that's why I cannot give you an exact release time.

If you can make sure the file path don't have unicode character (e.g. Greek letter, CJK), you can download the app with DTR func in github action page:
https://github.com/noonchen/STDF-Viewer/actions/runs/1799131928

**Comment by noonchen** [comment]
This functionality is going to be released, closing this feature request since it is already on the main branch.

**Comment by jbesancon-impinj** [comment]
Thanks very much for the link to the pre-release exe. It looks really good! The only thing I have noticed is that if there is a lot of text in a DTR, not all of it shown in the table. Other than that, it looks excellent!

**Comment by sbazili** [comment]
Hi,
Please note that with this version 3.4.0 I'm getting an error: "The file is not a valid STDF".
I guess it's something related to DTR records. We have many of them.

![image](https://user-images.githubusercontent.com/97961050/157107053-2a585939-8972-4f15-b030-427c6d4a3fae.png)

**Comment by noonchen** [comment]
@jbesancon-impinj can you post a screenshot of the issue? is the text being truncated or is it just extended to the border of cells?

**Comment by noonchen** [comment]
@sbazili There's only one possibility, there is an unrecognized record type in your file.

In the previous version, I skipped some records that are not required for visualizing, as well as the unknown records. 

However, in the main branch all 25 types of records are parsed, including DTR:
https://github.com/noonchen/STDF-Viewer/blob/307d2efca6f907b5c13c44f62a80bdaa98663404/deps/cystdf/cystdf_amalgamation.pyx#L156-L162
If the record type is not recognized, throw invalid stdf error:
https://github.com/noonchen/STDF-Viewer/blob/307d2efca6f907b5c13c44f62a80bdaa98663404/deps/cystdf/cystdf_amalgamation.pyx#L210-L215

If you believe it is a bug in STDF Viewer, you can send one of the file to my email for me to debug ;)
