### ISSUE TITLE
DUT Data Table - vertical view

### ISSUE THREAD

**Issue by sbazili** [noonchen/STDF-Viewer#89]
![DUT Data Table](https://user-images.githubusercontent.com/97961050/154802660-5b0d34f2-26a2-4d49-8b19-9b3f537f5509.PNG)

Hi,
Is it possible to support the vertical view, in addition to the horizontal view ? Maybe by some check-box to revert the view.
It means that 1 unit will have many lines, each line represents a new test.

**Comment by noonchen** [comment]
@sbazili thanks for your suggestion, but I'm super busy in the following months, I'll add this to the feature list.
