### ISSUE TITLE
Supported file list - feature request to add *.stdf.gz in selection

### ISSUE THREAD

**Issue by sbazili** [noonchen/STDF-Viewer#92]
Hi,
I see the tool support STDF that was GZIP'ed. 
This is very cool and can save us many disk space to save all everything in GZIP and still have the option to access the logs.

A small feature request:
There are 3 options when opening the file selection:
1) All supported Files (*.std, *.stdf, *.stdf*, *.gz, *.bz2)
2) STDF (*.std, *.stdf)
3) Compressed STDF (*.gz, *.bz2) <-- Is it possible to add here also *.stdf.gz ?

Thanks,
Stas

![Capture](https://user-images.githubusercontent.com/97961050/156012495-5476bbaa-1ff9-4e92-9f18-2179fbb13965.PNG)

**Comment by sbazili** [comment]
I think about it, let me correct the request. It's a small request by it can make our work a little bit easier.
I'm actually requesting to add 2 more formats in item #4. Compressed STDF (*.stdf.gz, *.stdf.bz2)
The reason for that is that we're saving our datalogs and additional formats in the same directory, everything is *.something.gz.
Having this filter (*.stdf.gz, *.stdf.bz2) will help to show only compressed STDF, and not any compressed file.

Please let me know if more clarification is needed.

**Comment by noonchen** [comment]
Sounds reasonable.
